version: '3.7'

services:
  pg-jwt-auth:
    volumes:
      - ./:${DOCKER_CONTAINER_APP_PATH}:${DOCKER_VOLUME_BIND_FLAG}
      - ${DOCKER_CONTAINER_APP_PATH}node_modules
      - ${DOCKER_CONTAINER_PLUGINS_PATH}node_modules
    ports:
      - ${DEFAULT_DEBUG_PORT}
      - ${DEFAULT_HTTP_PORT}
    environment:
      NODE_ENV: development
      GS_ENV: development
