name: Pg JWT Auth Container Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true      
      - name: Initialize
        run: yarn setup      
      - name: Test
        run: yarn test